version: "3.7"
services:
  app:
    image: 127.0.0.1:5000/node
    restart: always
    build: .
    ports: ["3000:3000"]
    volumes:
      - ./:/app
    deploy:
      mode: replicated
      replicas: 4
  mongo:
    container_name: mongo
    image: mongo
    ports: ["27017:27017"]